### ISSUE TITLE
Error with Node 4

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/kotatsu#102] opened 2016-02-18 14:31 UTC
When installing this boilerplate with Node 4 there are errors happening:

https://github.com/cerebral/cerebral-boilerplate

**Comment by Yomguithereal** [comment] 2016-02-18 17:06
Isn't one of the issues being that node 4 comes with npm 2?

**Comment by Yomguithereal** [comment] 2016-02-18 17:09
Installation completed succesfully on my side with node v4.3.1 and npm 2.14.12. However the bundle fails when using `npm start` because of some babel error.

**Comment by Yomguithereal** [comment] 2016-03-04 10:59
So, what shall I do about this :)?

**Comment by christianalfoni** [comment] 2016-03-06 16:21
Would suggest just adding to docs that Node 5 and NPM 3 is recommended? :-)

**Comment by Yomguithereal** [comment] 2016-03-08 10:49
Yup, could be nice indeed. But I am still not sure that it really does not work with node 4 & 0.12 etc.

**Comment by abalmos** [comment] 2016-03-08 12:37
@Yomguithereal I can confirm strange babel errors with node < 5. I actually
think it is an npm < 3 issue but we never tracked it down exactly...

**Comment by Yomguithereal** [comment] 2016-03-08 13:38
Well that's unfortunate. Warning on the documentation it is then, I guess.

**Comment by Yomguithereal** [comment] 2016-03-08 13:45
Just tested kotatsu on node `0.12.11` and it works.

**Comment by Yomguithereal** [comment] 2016-03-08 13:46
Just tested kotatsu on node 4.1.0 (Mac OS) and it works.

**Comment by Yomguithereal** [comment] 2016-03-08 13:47
Will try the boilerplate again but I'm having a hard time figuring out where the problem comes from.

**Comment by Yomguithereal** [comment] 2016-03-08 13:56
The issue with the boilerplate is that npm2 doesn't flatten and therefore doesn't have access to kotatsu's `babel-loader` and presets dependencies.

**Comment by Yomguithereal** [comment] 2016-03-08 13:57
I could try to be more clever in config merging but I am not sure this would be beneficial.

**Comment by Yomguithereal** [comment] 2016-03-09 11:11
I added a note in the documentation concerning npm3 etc. Can you tell me whether we can close this issue?

**Comment by bebraw** [comment] 2016-04-26 07:00
@christianalfoni Safe to close?

**Comment by christianalfoni** [comment] 2016-04-26 07:38
I am happy :)

**Closed** 2016-04-26 09:22 UTC
Labels: bug, documentation
